package dancingBallsPKG;


//a single "class" record for a midi data song.
//this record will hold what would be class data in supervised 
//learning, corresponding to a feature-based training example.
//this training example will be what is generated by a CondGAN 
//given this class record and a suitable latent variable input as input
public class myMidiDataClassRec {
	//composer tag - unique numeric tag for a particular composer
	
	

	public myMidiDataClassRec() {
		// TODO Auto-generated constructor stub
	}

}
