package dancingBallsPKG;

//a single "feature" example for a midi data song.
//this record will hold what would be feature-based training example 
//in supervised learning, linked with a corresponding "class" example
//this training example will be what is generated by a CondGAN given 
//the linked class record and a suitable latent variable input as input

//this record consists of note information for a sliding window of the song, 
//containing intervals of musical information spanning both time and 
//channels (instruments, or more broadly, features)

public class myMidiDataFtrRec {
	//window stride size - distance window moves per sampling - 1/2 window width
	public static float wStride;
	//window center location corresponding to this ftr record
	public float wLoc;

	public myMidiDataFtrRec() {
		// TODO Auto-generated constructor stub
	}

}
